#CQ1 - Why is the medication being prescribed?

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX pcdo: <http://sbmi.uth.edu/ontology/pcdo#>

SELECT DISTINCT ?idrug  ?itarget ?iacts
	WHERE { 
	?idrug rdf:type owl:NamedIndividual .
	?idrug pcdo:treats ?itarget .
	?idrug pcdo:acts_by ?iacts
}