#CQ3 - Any side effects with the medication?

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX pcdo: <http://sbmi.uth.edu/ontology/pcdo#>

SELECT DISTINCT ?idrug  ?reaction ?sign
	WHERE { 
	?idrug rdf:type owl:NamedIndividual .
	?idrug pcdo:may_cause ?reaction .
	OPTIONAL {?reaction pcdo:has_signs ?sign} .
}