#CQ4 - How is the medication given?

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX pcdo: <http://sbmi.uth.edu/ontology/pcdo#>


SELECT DISTINCT ?idrug ?form ?admin ?method
	WHERE { 
	?idrug rdf:type owl:NamedIndividual .
	?idrug pcdo:comes_in ?form
	OPTIONAL {?idrug pcdo:administered_in ?admin} .
	OPTIONAL {?form pcdo:delivered_by ?method} .
}

