#CQ7 - Do I need take my medication with food?

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX pcdo: <http://sbmi.uth.edu/ontology/pcdo#>


SELECT DISTINCT ?idrug ?foodinstruction 
	WHERE { 
	?idrug rdf:type pcdo:Drug .
	?idrug pcdo:has_special_instructions ?foodinstruction .
	?foodinstruction rdf:type pcdo:Special_Dietary_Instructions .
	?foodinstruction rdf:type pcdo:Special_Instructions_Involving_Food .
}