#CQ17 - I am taking asprin are there any interactions?

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX pcdo: <http://sbmi.uth.edu/ontology/pcdo#>


SELECT DISTINCT ?idrug ?combo
	WHERE { 
	?idrug rdf:type pcdo:Drug .
	?idrug pcdo:avoid_taking_with ?combo .
	# FILTER regex(str(?combo), "asprin", "i").
	?combo pcdo:has_drug_interactions_with ?asprin .
	FILTER regex(str(?asprin), "asprin", "i") .
}